#ifndef EMACHENT
#error "EMACHENT must be defined before including e_machine.h"
#endif

EMACHENT(NONE, "Unknown machine")
EMACHENT(M32, "AT&T WE32100")
EMACHENT(SPARC, "Sun SPARC")
EMACHENT(386, "Intel i386")
EMACHENT(68K, "Motorola 68000")
EMACHENT(88K, "Motorola 88000")
EMACHENT(IAMCU, "Intel MCU / 80486")
EMACHENT(860, "Intel i860")
EMACHENT(MIPS, "MIPS R3000 Big-Endian only")
EMACHENT(S370, "IBM System/370")
EMACHENT(MIPS_RS3_LE, "MIPS R3000 Little-Endian")
EMACHENT(PARISC, "HP PA-RISC")
EMACHENT(VPP500, "Fujitsu VPP500")
EMACHENT(SPARC32PLUS, "SPARC v8plus")
EMACHENT(960, "Intel 80960")
EMACHENT(PPC, "PowerPC 32-bit")
EMACHENT(PPC64, "PowerPC 64-bit")
EMACHENT(S390, "IBM System/390")
EMACHENT(SPU, "IBM SPU/SPC")
EMACHENT(V800, "NEC V800")
EMACHENT(FR20, "Fujitsu FR20")
EMACHENT(RH32, "TRW RH-32")
EMACHENT(RCE, "Motorola RCE")
EMACHENT(ARM, "ARM")
EMACHENT(SH, "Hitachi SH")
EMACHENT(SPARCV9, "SPARC v9 64-bit")
EMACHENT(TRICORE, "Siemens TriCore embedded processor")
EMACHENT(ARC, "Argonaut RISC Core")
EMACHENT(H8_300, "Hitachi H8/300")
EMACHENT(H8_300H, "Hitachi H8/300H")
EMACHENT(H8S, "Hitachi H8S")
EMACHENT(H8_500, "Hitachi H8/500")
EMACHENT(IA_64, "Intel IA-64 Processor")
EMACHENT(MIPS_X, "Stanford MIPS-X")
EMACHENT(COLDFIRE, "Motorola ColdFire")
EMACHENT(68HC12, "Motorola M68HC12")
EMACHENT(MMA, "Fujitsu MMA")
EMACHENT(PCP, "Siemens PCP")
EMACHENT(NCPU, "Sony nCPU")
EMACHENT(NDR1, "Denso NDR1 microprocessor")
EMACHENT(STARCORE, "Motorola Star*Core processor")
EMACHENT(ME16, "Toyota ME16 processor")
EMACHENT(ST100, "STMicroelectronics ST100 processor")
EMACHENT(TINYJ, "Advanced Logic Corp. TinyJ processor")
EMACHENT(X86_64, "AMD/Intel x86-64")
EMACHENT(PDSP, "Sony DSP Processor")
EMACHENT(PDP10, "Digital PDP-10")
EMACHENT(PDP11, "Digital PDP-11")
EMACHENT(FX66, "Siemens FX66 microcontroller")
EMACHENT(ST9PLUS, "STMicroelectronics ST9+ 8/16 microcontroller")
EMACHENT(ST7, "STmicroelectronics ST7 8-bit microcontroller")
EMACHENT(68HC16, "Motorola MC68HC16 microcontroller")
EMACHENT(68HC11, "Motorola MC68HC11 microcontroller")
EMACHENT(68HC08, "Motorola MC68HC08 microcontroller")
EMACHENT(68HC05, "Motorola MC68HC05 microcontroller")
EMACHENT(SVX, "Silicon Graphics SVx")
EMACHENT(ST19, "STMicroelectronics ST19 8-bit mc")
EMACHENT(VAX, "Digital VAX")
EMACHENT(CRIS, "Axis Communications 32-bit embedded processor")
EMACHENT(JAVELIN, "Infineon Technologies 32-bit embedded processor")
EMACHENT(FIREPATH, "Element 14 64-bit DSP Processor")
EMACHENT(ZSP, "LSI Logic 16-bit DSP Processor")
EMACHENT(MMIX, "Donald Knuth's educational 64-bit proc")
EMACHENT(HUANY, "Harvard University machine-independent object files")
EMACHENT(PRISM, "SiTera Prism")
EMACHENT(AVR, "Atmel AVR 8-bit microcontroller")
EMACHENT(FR30, "Fujitsu FR30")
EMACHENT(D10V, "Mitsubishi D10V")
EMACHENT(D30V, "Mitsubishi D30V")
EMACHENT(V850, "NEC v850")
EMACHENT(M32R, "Mitsubishi M32R")
EMACHENT(MN10300, "Matsushita MN10300")
EMACHENT(MN10200, "Matsushita MN10200")
EMACHENT(PJ, "picoJava")
EMACHENT(OPENRISC, "OpenRISC 32-bit embedded processor")
EMACHENT(ARC_A5, "ARC Cores Tangent-A5")
EMACHENT(XTENSA, "Tensilica Xtensa Architecture")
EMACHENT(VIDEOCORE, "Alphamosaic VideoCore processor")
EMACHENT(TMM_GPP, "Thompson Multimedia General Purpose Processor")
EMACHENT(NS32K, "National Semiconductor 32000 series")
EMACHENT(TPC, "Tenor Network TPC processor")
EMACHENT(SNP1K, "Trebia SNP 1000 processor")
EMACHENT(ST200, "STMicroelectronics ST200 microcontroller")
EMACHENT(IP2K, "Ubicom IP2xxx microcontroller family")
EMACHENT(MAX, "MAX Processor")
EMACHENT(CR, "National Semiconductor CompactRISC microprocessor")
EMACHENT(F2MC16, "Fujitsu F2MC16")
EMACHENT(MSP430, "Texas Instruments embedded microcontroller msp430")
EMACHENT(BLACKFIN, "Analog Devices Blackfin (DSP) processor")
EMACHENT(SE_C33, "S1C33 Family of Seiko Epson processors")
EMACHENT(SEP, "Sharp embedded microprocessor")
EMACHENT(ARCA, "Arca RISC Microprocessor")
EMACHENT(UNICORE, "Microprocessor series from PKU-Unity Ltd.  and MPRC of Peking University")
EMACHENT(EXCESS, "eXcess configurable cpu")
EMACHENT(DXP, "Icera Semi. Deep Execution Processor")
EMACHENT(ALTERA_NIOS2, "Altera Nios II")
EMACHENT(CRX, "National Semi. CompactRISC CRX")
EMACHENT(XGATE, "Motorola XGATE")
EMACHENT(C166, "Infineon C16x/XC16x")
EMACHENT(M16C, "Renesas M16C")
EMACHENT(DSPIC30F, "Microchip Technology dsPIC30F")
EMACHENT(CE, "Freescale Communication Engine RISC")
EMACHENT(M32C, "Renesas M32C")
EMACHENT(TSK3000, "Altium TSK3000")
EMACHENT(RS08, "Freescale RS08")
EMACHENT(SHARC, "Analog Devices SHARC family")
EMACHENT(ECOG2, "Cyan Technology eCOG2")
EMACHENT(SCORE7, "Sunplus S+core7 RISC")
EMACHENT(DSP24, "New Japan Radio (NJR) 24-bit DSP")
EMACHENT(VIDEOCORE3, "Broadcom VideoCore III")
EMACHENT(LATTICEMICO32, "RISC for Lattice FPGA")
EMACHENT(SE_C17, "Seiko Epson C17")
EMACHENT(TI_C6000, "Texas Instruments TMS320C6000 DSP")
EMACHENT(TI_C2000, "Texas Instruments TMS320C2000 DSP")
EMACHENT(TI_C5500, "Texas Instruments TMS320C55x DSP")
EMACHENT(TI_ARP32, "Texas Instruments App. Specific RISC")
EMACHENT(TI_PRU, "Texas Instruments Prog. Realtime Unit")
EMACHENT(MMDSP_PLUS, "STMicroelectronics 64bit VLIW DSP")
EMACHENT(CYPRESS_M8C, "Cypress M8C")
EMACHENT(R32C, "Renesas R32C")
EMACHENT(TRIMEDIA, "NXP Semi. TriMedia")
EMACHENT(QDSP6, "QUALCOMM DSP6")
EMACHENT(8051, "Intel 8051 and variants")
EMACHENT(STXP7X, "STMicroelectronics STxP7x")
EMACHENT(NDS32, "Andes Tech. compact code emb. RISC")
EMACHENT(ECOG1X, "Cyan Technology eCOG1X")
EMACHENT(MAXQ30, "Dallas Semi. MAXQ30 mc")
EMACHENT(XIMO16, "New Japan Radio (NJR) 16-bit DSP")
EMACHENT(MANIK, "M2000 Reconfigurable RISC")
EMACHENT(CRAYNV2, "Cray NV2 vector architecture")
EMACHENT(RX, "Renesas RX")
EMACHENT(METAG, "Imagination Tech. META")
EMACHENT(MCST_ELBRUS, "MCST Elbrus")
EMACHENT(ECOG16, "Cyan Technology eCOG16")
EMACHENT(CR16, "National Semi. CompactRISC CR16")
EMACHENT(ETPU, "Freescale Extended Time Processing Unit")
EMACHENT(SLE9X, "Infineon Tech. SLE9X")
EMACHENT(L10M, "Intel L10M")
EMACHENT(K10M, "Intel K10M")
EMACHENT(AARCH64, "AArch64 (64-bit ARM)")
EMACHENT(AVR32, "Amtel 32-bit microprocessor")
EMACHENT(STM8, "STMicroelectronics STM8")
EMACHENT(TILE64, "Tileta TILE64")
EMACHENT(TILEPRO, "Tilera TILEPro")
EMACHENT(MICROBLAZE, "Xilinx MicroBlaze")
EMACHENT(CUDA, "NVIDIA CUDA")
EMACHENT(TILEGX, "Tilera TILE-Gx")
EMACHENT(CLOUDSHIELD, "CloudShield")
EMACHENT(COREA_1ST, "KIPO-KAIST Core-A 1st gen")
EMACHENT(COREA_2ND, "KIPO-KAIST Core-A 2nd gen")
EMACHENT(ARC_COMPACT2, "Synopsys ARCompact V2")
EMACHENT(OPEN8, "Open8 RISC")
EMACHENT(RL78, "Renesas RL78")
EMACHENT(VIDEOCORE5, "Broadcom VideoCore V")
EMACHENT(78KOR, "Renesas 78KOR")
EMACHENT(56800EX, "Freescale 56800EX DSC")
EMACHENT(BA1, "Beyond BA1")
EMACHENT(BA2, "Beyond BA2")
EMACHENT(XCORE, "XMOS xCORE")
EMACHENT(MCHP_PIC, "Microchip 8-bit PIC(r)")
EMACHENT(KM32, "KM211 KM32")
EMACHENT(KMX32, "KM211 KMX32")
EMACHENT(EMX16, "KM211 KMX16")
EMACHENT(EMX8, "KM211 KMX8")
EMACHENT(KVARC, "KM211 KVARC")
EMACHENT(CDP, "Paneve CDP")
EMACHENT(COGE, "Cognitive Smart Memory Processor")
EMACHENT(COOL, "Bluechip CoolEngine")
EMACHENT(NORC, "Nanoradio Optimized RISC")
EMACHENT(CSR_KALIMBA, "CSR Kalimba")
EMACHENT(Z80, "Zilog Z80")
EMACHENT(VISIUM, "CDS VISIUMcore")
EMACHENT(FT32, "FTDI Chip FT32")
EMACHENT(MOXIE, "Moxie processor")
EMACHENT(AMDGPU, "AMD GPU")
EMACHENT(RISCV, "RISC-V")
EMACHENT(BPF, "Linux BPF - in-kernel VM")
EMACHENT(ALPHA, "Alpha")
