#ifndef PTYPEENT
#error "PTYPEENT must be defined before including p_type.h"
#endif

PTYPEENT(NULL)
PTYPEENT(LOAD)
PTYPEENT(DYNAMIC)
PTYPEENT(INTERP)
PTYPEENT(NOTE)
PTYPEENT(SHLIB)
PTYPEENT(PHDR)
PTYPEENT(TLS)
PTYPEENT(GNU_EH_FRAME)
PTYPEENT(GNU_STACK)
PTYPEENT(GNU_RELRO)
